services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev

    environment:
      SENDGRID_API_KEY: "mBPCrNO8GvV2xS4Q1LtZwEYQH/NcQ5ONy9NE5I/p+YrKCXJa5Xh1MWkd51zwlQr7n9WINfVRMaR5NLGdESeR9b0y62bZ"
      FROM_EMAIL: "blockade.web@gmail.com"
      DEV_EMAIL: "pT2Pqv2HPMIWlB0giL0swcFuQw/4LzN9Yob4"

    volumes:
      - .:/opt/app/api

    ports:
      - "80:3000"

secrets:
  sendgrid_api_key:
      environment: "SENDGRID_API_KEY"

  dev_email:
    environment: "DEV_EMAIL"

